service:
  name: "accountService"

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
      webpackConfig: ./webpack.config.js
      includeModules: true
  package:
  individually: true  
  authorizer:
    type: CUSTOM
    authorizerId: ${ssm:authorizerId}

provider:
  name: aws
  runtime: nodejs14.x
  timeout: 30
  region: us-east-2
  apiGateway:
    restApiId: ${ssm:restApiId}
    restApiRootResourceId: ${ssm:restApiRootResourceId}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SES:Publish
        - SES:SendRawEmail
      Resource: '*'
    - Effect: Allow
      Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Resource: '*'
    - Effect: Allow
      Action:
        - 'ssm:GetParameter'
        - 'ssm:GetParameters'
        - 'ssm:GetParameterHistory'
        - 'ssm:GetParametersByPath'
        - 'ssm:DescribeParameters'
      Resource: '*'
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: ${ssm:topicSnsDeletePortador}

functions:
  CreateAccount:
    handler: src/functions/CreateAccount.handler
    events:
      - sqs:
            arn: ${ssm:Sqs-create-account-fila}
      - http:
          path: account/create
          method: POST
          cors: true
  CreateOperation:
    handler: src/functions/CreateOperation.handler
    events:
      - http:
          path: account/createOperation
          method: POST
          cors: true
          authorizer: ${self:custom.authorizer}
  GetExtractByData:
    handler: src/functions/GetExtractByData.handler
    events:
      - http:
          path: account/getExtractByData
          method: GET
          request:
            parameters:
              querystrings:
                startDate: true
                endDate: true
                cpf: true
          cors: true
          authorizer: ${self:custom.authorizer}
  DeleteAccount:
    handler: src/functions/DeleteAccount.handler
    events:
      - http:
          path: account/deleteAccount
          method: DELETE
          request:
            parameters:
              querystrings:
                cpf: true
          cors: true
          authorizer: ${self:custom.authorizer}
  BlockOrDesblockAccount:
    handler: src/functions/BlockOrDesblockAccount.handler
    events:
      - http:
          path: account/blockOrUnlockAccount
          method: PUT
          cors: true
          authorizer: ${self:custom.authorizer}
  GetAccount:
    handler: src/functions/GetAccount.handler
    events:
      - http:
          path: account/getAccount
          method: GET
          cors: true
          authorizer: ${self:custom.authorizer}
                        

